name:                random-haskell-ideas
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/sjakobi/random-haskell-ideas#readme
license:             BSD3
author:              Simon Jakobi
maintainer:          simon.jakobi@gmail.com
copyright:           BSD3
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - semigroups

library:
  source-dirs:      src
  exposed-modules:
    - Lib

tests:
  doctests:
    ghc-options: -threaded -Wall
    source-dirs:
      - tests
    main: doctests.hs
    dependencies:
      - doctest
      - QuickCheck
